# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ced595fb9fdf62acf207a3a18735c8d9614d54fe32c99e6b07d5d8112dd8059c08225f2caa424a524d5c4ab6c54b467e4d1b3f7929ef1396846d57cf17c5b8e9

test:
  secret_key_base: bfbf81a55b04dcec6203cad13c72e4780adbb9e1002e3086c804bb01c1eb3d3333df5cec750229d53d66418c2c15a0cf333317a83faf9ee77eca08ea8553f367

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
